root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/job-service ./cmd/job-service"
  bin = "tmp/job-service"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "cassandra"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test\\.go"]

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true
