FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY . .

RUN go build -o execution-service ./cmd/execution-service

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/execution-service .

ENV EXECUTION_SERVICE_PORT=:50053

CMD ["./execution-service"]
