FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY . .

RUN go build -o execution-service ./cmd/execution-service

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/execution-service .

ENV EXECUTION_SERVICE_GRPC_PORT=:50053
ENV EXECUTION_SERVICE_HTTP_PORT=:8082

CMD ["./execution-service"]
