FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY . .

RUN go build -o scheduler-service ./cmd/scheduler-service

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/scheduler-service .

CMD ["./scheduler-service"]

# Expose ports for gRPC and HTTP
EXPOSE 50052
EXPOSE 8081
